FROM alpine:3.3
RUN apk add --update alpine-sdk
RUN curl -Ls https://github.com/rofl0r/proxychains-ng/archive/v4.11.tar.gz | tar xfvz - && \
    cd proxychains-ng-4.11 && ./configure && make && make install
